import '@/styles/globals.css'
import { AnimatePresence } from 'framer-motion'
import { Poppins } from 'next/font/google'
import Head from 'next/head'

const popis = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export default function App ({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Criss | Full-Stack Dev</title>
        <link rel='icon' href='/icon.svg' />
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={`${popis.className}`}>
        <AnimatePresence mode='wait'>
          <Component {...pageProps} />
        </AnimatePresence>
      </main>
    </>
  )
}
